version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: tapwal_app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name: tapwal_nginx
        restart: unless-stopped
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 8080:80
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
