version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: unless-stopped
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        ports:
            - 80:80
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
