name: Deploy Tapal API to Vultr

on:
  push:
    branches:
      - main # Deploy when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 2828 64.176.57.179 >> ~/.ssh/known_hosts
          ls -la ~/.ssh/  # Debugging step

      - name: Deploy Docker Containers on Tapwal VPS
        run: |
          echo "Starting Deployment via SSH..."
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -p 2828 gudofabi@64.176.57.179 << 'EOF'
          echo "Connected to VPS"

          # Navigate to the project directory
          cd /home/gudofabi/tapal-api-app

          # Pull latest code from GitHub
          git pull origin main

          # Ensure proper permissions for storage & cache
          sudo chown -R $(whoami):$(whoami) /home/gudofabi/tapal-api-app
          sudo chmod -R 775 /home/gudofabi/tapal-api-app/storage /home/gudofabi/tapal-api-app/bootstrap/cache

          # Stop and remove old containers
          docker-compose down

          # Remove old vendor directory and install dependencies inside the container
          docker exec -it tapwal_app bash -c "rm -rf /var/www/vendor && composer install"

          # ✅ Step 4: Verify Permissions for vendor directory
          docker exec -it tapwal_app bash -c "chown -R www-data:www-data /var/www/vendor"
          docker exec -it tapwal_app bash -c "chmod -R 775 /var/www/vendor"

          # Build and start new containers
          docker-compose up -d --build

          # Verify running containers
          docker ps

          echo "Deployment completed successfully."
          EOF
