name: Deploy Tapal REST API to Vultr

on:
  push:
    branches:
      - main # Deploy when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 2828 64.176.57.179 >> ~/.ssh/known_hosts
          ls -la ~/.ssh/  # Debugging step

      - name: Deploy Docker Containers on Tapwal VPS
        run: |
          echo "Starting Deployment via SSH..."
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -p 2828 gudofabi@64.176.57.179 << 'EOF'
          echo "Connected to VPS"

          # Navigate to the project directory
          cd /home/gudofabi/tapal-api-app

          # Pull latest code from GitHub
          git pull origin main

          # Stop and remove only the Tapwal containers
          echo "Stopping and removing tapwal containers..."
          docker stop tapwal_app tapwal_nginx || true
          docker rm tapwal_app tapwal_nginx || true

          # Remove old images to avoid caching issues
          echo "Pruning old Docker images..."
          docker system prune -a -f

          # Rebuild and restart only the Tapwal containers
          echo "Rebuilding and starting Tapwal containers..."
          docker compose up -d --build app nginx

          # Clear Laravel caches
          echo "Clearing Laravel caches..."
          docker exec -it tapwal_app php artisan config:clear
          docker exec -it tapwal_app php artisan cache:clear
          docker exec -it tapwal_app php artisan route:clear
          docker exec -it tapwal_app php artisan view:clear

          # Verify running containers
          echo "Checking running containers..."
          docker ps

          # Show Laravel logs (optional for debugging)
          docker logs tapwal_app --tail=50

          echo "Deployment completed successfully."
          EOF
