name: Docker Compose Operations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker and Docker Compose
        uses: docker/setup-buildx-action@v1

      - name: Stop and remove existing containers
        run: docker-compose down

      - name: Build and run containers
        run: docker-compose up -d --build

      - name: Wait for containers to be ready
        run: sleep 10 # Adjust sleep time based on your app's startup time

      - name: Install Composer dependencies and generate key in tapwal_app
        run: |
          docker exec tapwal_app composer install --no-interaction
          docker exec tapwal_app php artisan key:generate

      - name: Cleanup
        if: always()
        run: docker-compose down
